### ISSUE TITLE
Markaya ait modellerin listelenmesi

### ISSUE THREAD

**Issue by peyloride** [egegunes/yakit#1]
Yeni bir endpoint yaratıp markaya ait modelleri listeleyelim. Parametre olarak markanın id'si yerine adını alırsa seo açısından çok daha iyi olur.

**Comment by egegunes** [comment]
Hali hazirda `/models?brand=1` ile filtrelenebiliyor. Isim ile filtre istiyorsak veritabaninda unique olmasi gerekecektir?

**Comment by peyloride** [comment]
O zaman aynen unique olsun keza aynı isimde marka olması pek mümkün değil.
