### ISSUE TITLE
Model tablosuna eklenmesi gerekenler

### ISSUE THREAD

**Issue by peyloride** [egegunes/yakit#11]
type: Enum(int)
0. Supersport
1. Enduro
2. Cruiser
3. Commuter
4. Scooter
5. Naked
6. Cross

engince_cc: integer
engine_hp: integer

**Comment by egegunes** [comment]
> 0. Supersport
> 1. Enduro
> 2. Cruiser
> 3. Commuter
> 4. Scooter
> 5. Naked
> 6. Cross

Bunlar motora özel tiplermiş gibi, genel Model tablosuna koymak istediğine emin misin? Ya da otomobiller için de bu tip bir şey olacak mı?

**Comment by peyloride** [comment]
Otomobiller için de sedan, hatchback, SUV gibi tipler olacak, dolayısıyla model içinde olması mantıklı geldi. Ya da vehicle içinde de olabilir. Bilemedim

**Comment by egegunes** [comment]
Modelin otomobil/motor ayrimi icin de bunlari kullanabilir miyiz? Yoksa ayri bir field mi olmali? Bunlari kullansak da ben sana motor/otomobil diye donebilirim

**Comment by peyloride** [comment]
Bunları kullanarak motosiklet/otomobil ayrımı yapamayız ne yazık ki. Vehicle atacağımız için model tablosuna motor/otomobil olduğuna dair bir field eklemek gerekecek.
