### ISSUE TITLE
Year meselesi

### ISSUE THREAD

**Issue by peyloride** [egegunes/yakit#18]
Ya bu year'I Vehicle içinde tutmak pek hoş olmadı. Bununla ilgili birkaç sorun var.

Her modelin hangi yılları olduğunu tek tek veritabanına girmek çok zor bir iş. 1300'e yakın model var veritabanında. Dolayısıyla bunu kullanıcının girmesini sağlamak istiyorum. Gösterirken de daha önce girilen yılları gösterip ona ait bir istatistikler sunacağım. Şu anki vehicle modelinde bu iş çok karmaşıklaşıyor.

Önce kullanıcının girdiği yıl,  o modele ait herhangi bir vehicle ile eşleşiyor mu diye bakıyorum. Eşleşiyorsa ordan yürüyorum onda sorun yok. Ama eşleşmiyorsa o modelin kullanıcının girdiği yıla ait bir Vehicle objesini oluşturmam gerek. POST yaptım ekledim diyelim, sayfayı güncellemem gerek. POST'dan dönen ID'yi kullanarak tekrar Entry oluşturmam gerek. Çok karmaşıklaşıyor.

Year bilgisini neden Entry tablosunda tutmuyoruz diye düşündüm, bir sebep bulamadım. Vehicle tablosunu komple atıp, Year bilgisini Entry'de tutmak daha mantıklı geliyor bana şu an.

**Comment by egegunes** [comment]
Bence de mantikli :+1:
