### ISSUE TITLE
Yakıt tüketim verileri için endpoint

### ISSUE THREAD

**Issue by peyloride** [egegunes/yakit#4]
Entry adlı bir model olabilir.
- `vehicle_id`
- consumption (float) - 100 km ortalamadaki veriyi tutacak: 2.5, 3.7, 6.2 gibi
- message (string)
- usage_type - (integerfield) : kullanım tipini ifade edecek. Şehir içi - uzun yol var şu an. 

Aynı endpoint için CRUD işlemlerini yapabiliyor olmamız gerekiyor.

**Comment by egegunes** [comment]
Endpoint'leri ekledim. Listeleme yaparken neye gore filtrelemek istiyorsun?

**Comment by peyloride** [comment]
Model ve yıla göre olmalı. Mesela Honda marka 2018 üretimli CBR modelinin tüketim verileri gibi. Model adının birden fazla markada tekrar etmesi pek olası değil, dolayısyıla model ve yıl birlikte unique olması yeterli.

**Comment by egegunes** [comment]
su anda `model + yil = vehicle` gibi bir durum var, dolayisiyla `/entries/?vehicle=1` seklinde olabilir. bence model ve markaya gore de olmali: `/entries/?model=1` ve `/entries/?brand=1` gibi

**Comment by peyloride** [comment]
Modele göre yine bir nebze anlamlı fakat markaya göre filtrelemenin bir mantığını göremedim. Honda araçlar az ya da çok yakıyor diyemeyiz, içinde az yakan da var çok yakan da.

**Comment by egegunes** [comment]
Honda araclari en az yakandan en cok yakana siralamak vs gibi isler icin guzel olabilir diye dusundum

**Comment by peyloride** [comment]
Şu an için böyle bi sayfamız yok ama mantıklı. Olsun bence böyle bir filtre.

**Comment by peyloride** [comment]
Sanırım bu işi yayına almamışsın henüz, 404 veriyor /entries endpointi. Mümkün olunca alabilir miyiz?

**Comment by egegunes** [comment]
yayinda

**Comment by peyloride** [comment]
http://yakit.testenv.site/entries 500 dönüyor şu an. "could not get entries" yazıyor sadece

**Comment by egegunes** [comment]
migration'i yaptim

**Comment by peyloride** [comment]
Eline sağlık
